---

- name: nsqlookupdinit | create the nsqlookupd init script
  copy: src=nsqlookupd.init dest=/etc/init.d/nsqlookupd mode=755
  register: nsqlookupd_task_init

- name: nsqlookupdinit | create the nsqlookupd config file
  template: src=nsqlookupd.conf.j2 dest=/usr/local/etc/nsqlookupd.conf
  register: nsqlookupd_task_conf

# - name: nsqlookupdinit | check for data directory
#   stat: path=/var/lib/nsq
#   register: nsqlookupdinit_data_dir_exists

# - name: nsqlookupdinit | create nsqlookupd data directory
#   command: mkdir /var/lib/nsq
#   when: nsqlookupdinit_data_dir_exists is not defined

- name: nsqlookupdinit | start nsqlookupd
  service: name=nsqlookupd state=started enabled=true

- name: nsqlookupdinit | restart nsqlookupd
  service: name=nsqlookupd state=restarted
  when: nsqlookupd_task_conf and nsqlookupd_task_conf.changed
